spring.application.name=demo
spring.config.import=optional:file:.env[.properties]

server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3307/agendamentos_db
?createDatabeseIfNotExist=true
&useSSL=false
&allowPublicKeyRetrieval=true
&serverTimezone=America/Sao_Paulo

spring.datasource.username=root

spring.datasource.password=senac

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

# Configuração do Mail Sender
# criptografia SSL/TLS de acordo com mailtrap
spring.mail.port=25
spring.mail.host=sandbox.smtp.mailtrap.io
# É necessário colocar um email responsável para enviar o link/código para alterar senha
# no momento foi utilizando e-mail pessoal para esse teste
spring.mail.username=${MAILTRAP_USER_SANDBOX}
spring.mail.password=${MAILTRAP_PASS_SANDBOX}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
