spring.application.name=demo
spring.config.import=optional:file:.env[.properties]

server.port=8080

?createDatabeseIfNotExist=true
&useSSL=false
&allowPublicKeyRetrieval=true
&serverTimezone=America/Sao_Paulo

spring.datasource.url=${DB_URL}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Sao_Paulo
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.mail.port=25
spring.mail.host=sandbox.smtp.mailtrap.io

spring.mail.username=${MAILTRAP_USER_SANDBOX}
spring.mail.password=${MAILTRAP_PASS_SANDBOX}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
